#!/usr/bin/env bash

set -eu 

echo -n starting docker... 

nohup dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375  > nohup.out 2>&1 &

while :
do 
    docker ps > /dev/null 2>&1 && break || sleep 2
    ps | grep dockerd > /dev/null || (echo "docker failed to start"; cat nohup.out ; exit 1)
done

echo DONE 

exec "$@"