#!/usr/bin/env bash

set -e

echo -n starting docker... 

nohup dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375  > dockerd.out 2>&1 &

while :
do 
    docker ps > /dev/null 2>&1 && break || sleep 2
    ps | grep dockerd > /dev/null || (echo "FAIL, see logs below:"; cat dockerd.out ; exit 1)
done

echo SUCCESS 

set +e

exec "$@"